Some new Pacman cheats, Quicksync, SearchAndDo and Nvim-recover

diff --git a/search-and-do b/search-and-do
--- a/search-and-do
+++ b/search-and-do
@@ -1,43 +1,45 @@
 #!/bin/sh
-
+#
+# ---------------------------------------------------------------------------------------
+#  Description
+# ---------------------------------------------------------------------------------------
+#
 # Description:
 # This is a brief description of my script
 #
 # Author:
 # Jorge Barrientos Poisson
 #
-# ChangeLog:
-# 2020.02.03 | 1st revision of this template
-# 2021.04.06 | Some small styling fixes
+# ---------------------------------------------------------------------------------------
+#  ChangeLog
+# ---------------------------------------------------------------------------------------
+#
+#  2020.02.03 | 1st revision of this template
+#  2021.04.06 | Some small styling fixes
+#  2024.03.19 | Refactoring into the new template
+#
+# ---------------------------------------------------------------------------------------
+#  Variables and Settings
+# ---------------------------------------------------------------------------------------
 
-# Standard functions and variables for every script
-	
 SCRIPT_NAME=$( basename $0 )
-SCRIPT_VERSION="0.2"
+SCRIPT_VERSION="2024.03.19"
+
+# ---------------------------------------------------------------------------------------
+#  Base functions
+# ---------------------------------------------------------------------------------------
 
 usage() {
 	printf "usage: %s [-h]\n" $SCRIPT_NAME
-	printf "   -n,   --name     Search by filename (accepts wildcards)"
-	printf "   -h,   --help     show this help message\n"
-	printf "         --debug    developer's mode\n"
+	printf "         --debug          developer mode\n"
+	printf "   -h,   --help           show this help message\n"
+	printf "   -v,   --verbose        verbose mode\n"
+	printf "         --version        show current version\n"
+	printf "         --test           an empty example \'test\' action\n"
 }
 
 version() {
-	printf "\e[33m%s\e[0m version \e[33m%s\e[0m.\n" $SCRIPT_NAME $SCRIPT_VERSION	
-}
-
-newline_set() {
-	NEWLINE="YES"	
-}
-
-newline_check() {
-	[ "$NEWLINE" == "YES" ] && echo
-	NEWLINE="NO"
-}
-
-defaults() {
-	SEARCH_PATH="."
-	NEWLINE="NO"
+	printf "  * \e[33m%s\e[0m version \e[33m%s\e[0m\n" $SCRIPT_NAME $SCRIPT_VERSION
 }
 
 check_args() {
@@ -52,7 +54,6 @@ check_args() {
 		do
 			# list of accepted arguments
 			case "$1" in
-
 				# default help option
 				"-h"|"--help")
 					usage
@@ -63,102 +64,140 @@ check_args() {
 					exit 0
 					;;
 				"--debug")
-					DEBUG="YES"
+					DEBUG="TRUE"
 					;;
 				# all user defined opts handled by user_args
 				*)
 					user_args "$@"
 					;;
-			esac			
-	
+			esac
 			# removes the first item from the list of given arguments ('$@')
 			shift
 		done	
 	fi
 }
 
+# ---------------------------------------------------------------------------------------
+#  Standard Functions
+# ---------------------------------------------------------------------------------------
+
+defaults() {
+	DEFAULT_DEBUG="FALSE"
+	DEFAULT_LAST_ARGUMENT_NEEDED="TRUE"
+
+	# conditional oneliners ( if/then/else == []/&&/|| )
+	[ -z $DEBUG ] && DEBUG="$DEFAULT_DEBUG"
+	[ -z $LAST_ARGUMENT_NEEDED ] && LAST_ARGUMENT_NEEDED="$DEFAULT_LAST_ARGUMENT_NEEDED"
+}
+
 user_args() {
-
-	# last argument is mandatory (given it's not --help or --version)
-	if [ $# -eq 1 ];
-	then
-		SEARCH_EXPR="$1"
-	fi
-
 	case $1 in
-		"-m"|"--move")
-			ACTION_MOVE="YES"
-			if [ ! -z "$2" ];
+		# insert user defined parameters
+		"-v"|"--verbose")
+			VERBOSE="TRUE"
+			;;
+		"-l|--list")
+			ACTION="list"
+			;;
+		"-x|--extract")
+			ACTION="extract"
+			;;
+		*)
+			if [ $# -eq 1 ];
 			then
-				DESTINATION="$2"
-			else
-				printf "\e[31mERROR:\e[0m Destination path not specified. Aborting!\n"
-				exit 1
+				LAST_ARGUMENT="$1"		
 			fi
 			;;
-		"-p"|"--path")
-			SEARCH_PATH="$2"
-			;;
-		"-x"|"--extract")
-			ACTION_EXTRACT="YES"
-			;;	
 	esac
 }
 
-actions() {
-
-	# ACTION: Find files first
-	printf "\n\e[33m-->\e[0m Searching for files matching \e[33m%s\e[0m wildcard expression ..." $SEARCH_EXPR
-
-	LIST=$( find "$SEARCH_PATH" -name "$SEARCH_EXPR" -type f -print )
-
-	if [ -z "$LIST" ];
+check_essentials() {
+	if [ "$LAST_ARGUMENT_NEEDED" = "TRUE" ];
 	then
-		# if no match is found, abort and exit
-		printf " \e[91mNO MATCH\e[0m\n\n"
-		exit 1
-	else
-		printf "\n\n"
-		# iterate through every item found
-		for i in $LIST;
-		do
-			ITEM_PATH="$( dirname $i )" 
-			ITEM_FILE="$( basename $i )"
-			printf "\e[33m-->\e[0m Found file \e[33m%s\e[0m\n" "$i"	
-
-			# extract item to its current folder
-			if [ "$ACTION_EXTRACT" == "YES" ];
-			then
-				printf "\e[33m-->\e[0m Extracting file \e[33m%s\e[0m to \e[33m%s\e[0m ..." "$ITEM_FILE" "$ITEM_PATH"
-				lha -xq2w="$ITEM_PATH" "$i" && printf " \e[92mOK\e[0m\n"
-				newline_set
-			fi
-
-			# move item to a common destination
-			if [ "$ACTION_MOVE" == "YES" ];
-			then			
-				mv "$i" "$DESTINATION" && printf "\e[33m-->\e[0m Moving \e[33m%s\e[0m to \e[33m%s\e[0m\n" $ITEM_FILE $DESTINATION
-				newline_set
-			fi
-
-			newline_check
-		done
-
+		if [ -z "$LAST_ARGUMENT" ];
+		then
+			printf "\e[31m-!> ERROR:\e[0m A last argument must be specified\n"
+			exit 1
+		fi
 	fi
 }
+
+action() {
+	
+	SEARCH="$LAST_ARGUMENT"
+
+	LIST=$( find . -type f -name "$SEARCH" -print )
+
+	case $ACTION in 
+		"list")
+			do_list
+			;;
+		*)
+			printf "\e[31m-!> ERROR:\e[0m ACTION variable \e[31m%s\e[0m not recognised\n" "$ACTION"
+			exit 1
+			;;
+	esac
+}
+
+# ---------------------------------------------------------------------------------------
+#  User defined functions
+# ---------------------------------------------------------------------------------------
+
+check_readable_file() {
+
+	TEST_FILE="$1"
+
+	if [ ! -r "$TEST_FILE" ];
+	then
+		printf "\e[31m-!> ERROR:\e[0m file \e[31m%s\e[0m not found or readable.\n" "$TEST_FILE"
+		exit 1
+	fi
+}
+
+check_folder() {
+
+	TEST_FOLDER="$1"
+
+	if [ ! -r "$TEST_FOLDER" ];
+	then
+		printf "\e[31m-!> ERROR:\e[0m folder \e[31m%s\e[0m not found.\n" "$TEST_FOLDER"
+		exit 1
+	fi
+}
+
+read_config() {
+
+	CONFIG_FILE="$1"
+	
+	# remove all empty lines and lines starting with a space
+	sed '/^#/d' "$CONFIG_FILE" | sed '/^ /d' | sed '/^$/d'
+}
+
+do_list() {
+	for item in "$LIST";
+	do
+		printf "--> %s\n" "$item"
+	done
+
+#			printf "\e[34m-!>\e[0m Debugging \e[34m%s\e[0m function:\n" 'do_example'
+#			printf "    \e[34m>\e[0m example line\n"
+}
+
+# ---------------------------------------------------------------------------------------
+#  Main block
+# ---------------------------------------------------------------------------------------
 
 main() {
-	# prerequisites of the script to be checked BEFORE any argument evalutation
-	defaults
 	check_args "$@"
-	# Execute standard OR debug version of the script
-	if [ -z $debugmode ];
-	then
-		version
-		actions
-	else
-		printf "\e[31mDEBUG:\e[0m script %s running\n" $scriptname
-	fi
+	defaults
+	check_essentials
+	# build_syntax
+	version
+	action
 }
+
+# ---------------------------------------------------------------------------------------
+#  Main call
+# ---------------------------------------------------------------------------------------
 
 main "$@"
